sonar.projectKey=mix-sonarqube
sonar.projectName=Mix SonarQube
sonar.projectVersion=0.1.0
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarqube.hpopp.dev
sonar.coverageReportPaths=cover/sonar-coverage.xml
